jbosstools/jbosstools-javaee

batch/plugins/org.jboss.tools.batch.core/META-INF/MANIFEST.MF
batch/plugins/org.jboss.tools.batch.core/src/org/jboss/tools/batch/internal/core/scanner/BatchArchiveDetector.java
cdi/plugins/org.jboss.tools.cdi.core/META-INF/MANIFEST.MF
cdi/plugins/org.jboss.tools.cdi.core/src/org/jboss/tools/cdi/internal/core/scanner/lib/BeanArchiveDetector.java

Jandex API is incapsulated in common and not exported.BeanArchiveDetector

JBIDE-19820 Batch feature makes wildfly import way slower

---

batch/plugins/org.jboss.tools.batch.ui/src/org/jboss/tools/batch/ui/editor/internal/action/OpenOrCreateArtifactActionHandler.java
batch/plugins/org.jboss.tools.batch.ui/src/org/jboss/tools/batch/ui/editor/internal/model/JobXMLEditor.sdef

Added activation Contlol+Mouse on text field.

JBIDE-20005 Navigation to Batch artifacts from properties editor

---

batch/plugins/org.jboss.tools.batch.ui/src/org/jboss/tools/batch/ui/editor/internal/action/BrowseRefActionHandler.java

Fixed: 'the field is set to org.eclipse.sapphire.services.ContentProposal@708cb2fa instead of the real value.

JBIDE-19993 Add possibility to browse for "ref" elements in Design and Diagram tabs

---

batch/plugins/org.jboss.tools.batch.core/src/org/jboss/tools/batch/internal/core/impl/BatchBuilder.java
cdi/plugins/org.jboss.tools.cdi.core/src/org/jboss/tools/cdi/core/CDICoreBuilder.java

JavaModelManager.cacheZipFiles(Object) is used to prevent JDT
from creating new ZipFiles for each request during one build.

JBIDE-20593 JBoss Tools builders are very slow with large jar libraries

---

jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/JsfUiPreferencesPagesTest.java

Removed @Test annotation from disabled tests (name starting with _test).

JBIDE-21058 JSF tests fail

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/Project.java

[JBIDE-24013] - compile failed in org.jboss.tools.cdi.ui.test

---

batch/plugins/org.jboss.tools.batch.core/src/org/jboss/tools/batch/internal/core/validation/BatchValidator.java

JBIDE-23656 - Missing validation of step listener with empty attribute ref

---

jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CADefaultELStartingCharTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAELApplyMethodProposalTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAELBeanPropertyTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAELFunctionsTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAELInsideTagBodyInJspFileTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAELNoTagProposalsInELTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAForELJavaAndJSTCompareTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAJsfAddInfoInELMessagesTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAJsfMessagesProposalsFilteringTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAJsfMessagesProposalsTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAJsfPredictiveTagNameProposalsTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CAJsfResourceBundlePropertyApplyTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CANotEmptyWhenThereIsNoSpaceBetweenInvertedCommandsInAttributeJBIDE1759Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/CASuggestsNotOnlyELProposalsJBIDE2437Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JavaClassContentAssistProviderTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JsfJBide3845Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JsfJspJbide1704Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JsfJspJbide1717Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JsfJspJbide6259Test.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/ca/test/JspElFunctionsTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/jsp/hover/ELTooltipTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/AddJSFCapabilitiesTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/JSFNaturesInfoDialog_JBIDE5701.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/JSPProblemMarkerResolutionTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/JsfUiPreferencesPagesTest.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/KbNaturesInfoDialog_JBIDE6125.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/TaglibXMLUnformatedDTD_JBIDE5642.java
jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/TestPaletteWizards.java

Signed-off-by: Dmitrii Bocharov <dbocharo@redhat.com>
don't know a "smarter" way to find out what test hangs on Mac
@jeffmaury @nickboldt please, merge

jbide-24379: add logging to find out reason for timeout failures

---

jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/NaturesInfoDialogTest.java

@jeffmaury @nickboldt could you, please, merge it.
It would be also great if you could give me push access in order not to disturb you every time

jbide-24379: add more logging to JSFNaturesInfoDialog_JBIDE5701 test

---

jsf/tests/org.jboss.tools.jsf.ui.test/src/org/jboss/tools/jsf/ui/test/NaturesInfoDialogTest.java

Signed-off-by: Dmitrii Bocharov <dbocharo@redhat.com>

jbide-24379: close all editors when tearDown to unblock UI

---

cdi/plugins/org.jboss.tools.cdi.ui/src/org/jboss/tools/cdi/ui/preferences/CDISettingsPreferencePage.java

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

JBIDE-12575 Build project when CDI is enabled via Project Properties

---

jsf/test-framework/org.jboss.tools.jsf.reddeer/META-INF/MANIFEST.MF
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/ImportJSFWarWizard.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/ImportWebWarWizardPage.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/JSFNewProjectFirstPage.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/JSFNewProjectSecondPage.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/JSFNewProjectWizard.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/WebComponentExportWizardPage.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/editor/FacesConfigEditor.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/editor/FacesConfigSourceEditor.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/editor/WebXmlEditor.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/editor/WebXmlSourceEditor.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/wizard/project/ImportProjectWizard.java

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-24943 Refactoring jsf.reddeer plugin for RedDeer2

---

jsf/test-framework/org.jboss.tools.jsf.reddeer/META-INF/MANIFEST.MF
jsf/test-framework/org.jboss.tools.jsf.reddeer/pom.xml
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/ImportJSFWarWizard.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/src/org/jboss/tools/jsf/reddeer/ui/editor/FacesConfigEditor.java

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

Repair JSF itests

---

batch/itests/pom.xml
batch/tests/pom.xml
cdi/tests/pom.xml
jsf/tests/pom.xml
seam/tests/pom.xml

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

Add parameter to poms to skip particular tests

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/Project.java
jsf/tests/org.jboss.tools.jsf.test/src/org/jboss/tools/jsf/plugin/JsfTestPlugin.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-26625: fix broken build due to 2019-06.M1

---

cdi/tests/org.jboss.tools.cdi.core.test/META-INF/MANIFEST.MF

JBIDE-26716 : fix compile error

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/JavaProject.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-27009: Fix compilation error due to 2019-12

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/Type.java
jsf/test-framework/org.jboss.tools.jsf.reddeer/META-INF/MANIFEST.MF

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-27301: fix RedDeer dependencies

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/Type.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-27316: javaee build is broken with 2020-06RC2 TP

---

cdi/tests/org.jboss.tools.cdi.ui.test/src/org/jboss/tools/cdi/ui/test/testmodel/Type.java

JBIDE-27560: fix for Java15 patch

---

.github/workflows/build_test.yml

JBIDE-27832: temporary fix for javaee baseline comparison

---

.github/workflows/build_test.yml

JBIDE-27868 : disable cdi and seam tests in PR checks

---

.github/workflows/build_test.yml

JBIDE-27832: revert temporary fix for baselinecomparison
